version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
    groups:
      typescript-eslint:
        patterns:
          - 'typescript-eslint'
          - '@typescript-eslint/*'
        update-types:
          - 'minor'
          - 'patch'
    open-pull-requests-limit: 10
    labels:
      - 'npm'
    reviewers:
      - 'ryansmith108'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
    groups:
      github-actions:
        patterns: ['*']
    open-pull-requests-limit: 5
    labels:
      - 'github-actions'
    reviewers:
      - 'ryansmith108'
