/**
 * SMI-1788: SubagentGenerator - Generate companion subagent definitions
 *
 * Creates subagent definitions for skills that benefit from parallel
 * execution with context isolation. Subagents enable:
 * - 37-97% token savings through context isolation
 * - Parallel execution of heavy operations
 * - Specialized tool access per agent
 *
 * Part of the Skillsmith Optimization Layer for transforming
 * community skills into more performant versions.
 *
 * SMI-6276 (Wave 6 Step 1): companion-agent frontmatter is now generated
 * per TARGET CLIENT via `SubagentGenerator.client-profiles.ts` — this file
 * no longer emits Claude-native tool names / a Claude `model:` value
 * unconditionally for every client `COMPANION_AGENT_TARGETS` writes a
 * companion file for. Types split to `.types.ts`, pure helpers split to
 * `.helpers.ts` (500-line standard).
 */

// Re-export types for public API (SMI-6276 split — see SubagentGenerator.types.ts)
export type {
  ClaudeModel,
  SubagentDefinition,
  SubagentGenerationResult,
} from './SubagentGenerator.types.js'
export { CLAUDE_MODELS } from './SubagentGenerator.types.js'

import type { SkillAnalysis } from './SkillAnalyzer.js'
import { CANONICAL_CLIENT, type ClientId } from '../install/paths.js'
import { getSubagentGenerationProfile, mapToolNames } from './SubagentGenerator.client-profiles.js'
import {
  CLAUDE_MODELS,
  type ClaudeModel,
  type SubagentGenerationResult,
} from './SubagentGenerator.types.js'
import {
  MAX_SUBAGENT_NAME_LENGTH,
  generateToolGuidelines,
  OMITTED_TOOLS_GUIDANCE,
  generateClaudeMdSnippet,
  extractTriggerPhrases,
  determineModel,
  detectTools,
} from './SubagentGenerator.helpers.js'

/**
 * Generate subagent markdown content
 *
 * SMI-6276 (Wave 6 Step 1): frontmatter shape is now driven by the target
 * client's generation profile (`SubagentGenerator.client-profiles.ts`) —
 * `Read, Write, Bash, WebFetch, Grep, Glob, WebSearch` plus a Claude
 * `model:` value are no longer emitted unconditionally for every client.
 */
function generateSubagentContent(
  name: string,
  description: string,
  triggerPhrases: string[],
  tools: string[],
  model: ClaudeModel,
  client: ClientId
): string {
  const triggerString =
    triggerPhrases.length > 0
      ? triggerPhrases.map((p) => `"${p}"`).join(', ')
      : '[describe trigger conditions]'

  const profile = getSubagentGenerationProfile(client)

  // SMI-6276 pr-reviewer finding: `description` is free text sourced from
  // the SKILL.md being transformed — an unquoted plain YAML scalar breaks
  // if it contains `: ` (reinterpreted as a nested key) or ` #` (truncated
  // as a comment). JSON.stringify() produces a valid YAML double-quoted
  // scalar (YAML's double-quote escaping is a superset of JSON's), so this
  // composes the full description+trigger text as a plain JS string FIRST,
  // then quotes the whole thing once — not per-field — so the result is
  // safe regardless of what the source content contains.
  const frontmatterLines = [
    '---',
    `name: ${name}`,
    `description: ${JSON.stringify(`${description} Use when ${triggerString}.`)}`,
  ]
  if (profile.includeSkillsField) {
    frontmatterLines.push(`skills: ${name.replace('-specialist', '')}`)
  }
  if (profile.toolsPolicy === 'claude-native') {
    frontmatterLines.push(`tools: ${tools.join(', ')}`)
  } else if (profile.toolsPolicy === 'mapped-array') {
    // SMI-6276: this client expects a YAML array of ITS OWN tool names, not
    // a Claude-shaped comma list — never emit the unmapped/mis-shaped value
    // (the AntiGravity docs' own "Known Issue" warns an unmapped name can
    // hang the subagent process on invocation). Omit the key entirely when
    // nothing maps, rather than an empty `tools: []` that says nothing.
    const mappedTools = mapToolNames(tools, profile)
    if (mappedTools.length > 0) {
      frontmatterLines.push('tools:', ...mappedTools.map((tool) => `  - ${tool}`))
    }
  }
  frontmatterLines.push(...profile.extraFrontmatterLines)
  if (profile.modelPolicy === 'claude-enum') {
    frontmatterLines.push(`model: ${model}`)
  }
  frontmatterLines.push('---')

  const toolGuidelines =
    profile.toolsPolicy === 'claude-native' ? generateToolGuidelines(tools) : OMITTED_TOOLS_GUIDANCE

  return `${frontmatterLines.join('\n')}

## Operating Protocol

1. Execute the ${name.replace('-specialist', '')} skill for the delegated task
2. Process all intermediate results internally
3. Return ONLY a structured summary to the orchestrator

## Output Format

- **Task:** [what was requested]
- **Actions:** [what you did]
- **Results:** [key outcomes, max 3-5 bullet points]
- **Artifacts:** [file paths or outputs created]

Keep response under 500 tokens unless explicitly requested otherwise.

## Tool Usage Guidelines

${toolGuidelines}

## Error Handling

If the task cannot be completed:
- Report specific blocking issue
- Suggest alternative approaches
- Do not retry indefinitely

---

*Generated by Skillsmith Optimization Layer*
`
}

/**
 * Generate a companion subagent for a skill
 *
 * @param skillName - The name of the skill
 * @param description - The skill's description
 * @param content - The full SKILL.md content
 * @param analysis - Analysis from SkillAnalyzer
 * @param client - SMI-6276: target client for the generated companion-agent
 *   frontmatter shape (default: canonical / `claude-code`, preserving prior
 *   behavior for every existing caller). See `SubagentGenerator.client-profiles.ts`.
 * @returns Subagent generation result
 */
export function generateSubagent(
  skillName: string,
  description: string,
  content: string,
  analysis: SkillAnalysis,
  client: ClientId = CANONICAL_CLIENT
): SubagentGenerationResult {
  // SMI-1815: Validate skill name is non-empty
  if (!skillName || skillName.trim() === '') {
    return {
      generated: false,
      reason: 'Skill name is required for subagent generation',
    }
  }

  // Check if subagent is recommended
  if (!analysis.toolUsage.suggestsSubagent && analysis.lineCount < 300) {
    return {
      generated: false,
      reason:
        'Skill does not have heavy tool usage or complexity that would benefit from a subagent',
    }
  }

  // Detect tools from content (supplement analysis)
  const detectedTools = detectTools(content)
  const allTools = Array.from(new Set([...analysis.toolUsage.detectedTools, ...detectedTools]))

  // Extract trigger phrases
  const triggerPhrases = extractTriggerPhrases(description, content)

  // Determine model
  const model = determineModel(analysis.toolUsage, analysis.lineCount)

  // SMI-1819: Generate subagent name with length limit
  const suffix = '-specialist'
  const maxBaseLength = MAX_SUBAGENT_NAME_LENGTH - suffix.length
  const baseName = skillName.length > maxBaseLength ? skillName.slice(0, maxBaseLength) : skillName
  const subagentName = `${baseName}${suffix}`

  // Generate subagent description
  const subagentDescription = description || `Specialist agent for ${skillName} operations`

  // Generate content
  const subagentContent = generateSubagentContent(
    subagentName,
    subagentDescription,
    triggerPhrases,
    allTools,
    model,
    client
  )

  // Generate CLAUDE.md snippet
  const claudeMdSnippet = generateClaudeMdSnippet(
    skillName,
    subagentDescription,
    triggerPhrases,
    allTools,
    model
  )

  return {
    generated: true,
    subagent: {
      name: subagentName,
      description: subagentDescription,
      triggerPhrases,
      tools: allTools,
      model,
      content: subagentContent,
    },
    claudeMdSnippet,
  }
}

/**
 * Generate a minimal subagent for skills that don't need full analysis
 *
 * @param skillName - The name of the skill
 * @param description - The skill's description
 * @param content - The full SKILL.md content
 * @param client - SMI-6276: target client for the generated companion-agent
 *   frontmatter shape (default: canonical / `claude-code`, preserving prior
 *   behavior for every existing caller). See `SubagentGenerator.client-profiles.ts`.
 * @returns Subagent generation result
 */
export function generateMinimalSubagent(
  skillName: string,
  description: string,
  content: string,
  client: ClientId = CANONICAL_CLIENT
): SubagentGenerationResult {
  // SMI-1815: Validate skill name is non-empty
  if (!skillName || skillName.trim() === '') {
    return {
      generated: false,
      reason: 'Skill name is required for subagent generation',
    }
  }

  const detectedTools = detectTools(content)
  const triggerPhrases = extractTriggerPhrases(description, content)

  // Default to sonnet for minimal subagents
  const model: ClaudeModel = CLAUDE_MODELS.SONNET

  // SMI-1819: Generate subagent name with length limit
  const suffix = '-specialist'
  const maxBaseLength = MAX_SUBAGENT_NAME_LENGTH - suffix.length
  const baseName = skillName.length > maxBaseLength ? skillName.slice(0, maxBaseLength) : skillName
  const subagentName = `${baseName}${suffix}`
  const subagentDescription = description || `Specialist agent for ${skillName} operations`

  const subagentContent = generateSubagentContent(
    subagentName,
    subagentDescription,
    triggerPhrases,
    detectedTools,
    model,
    client
  )

  const claudeMdSnippet = generateClaudeMdSnippet(
    skillName,
    subagentDescription,
    triggerPhrases,
    detectedTools,
    model
  )

  return {
    generated: true,
    subagent: {
      name: subagentName,
      description: subagentDescription,
      triggerPhrases,
      tools: detectedTools,
      model,
      content: subagentContent,
    },
    claudeMdSnippet,
  }
}

export default { generateSubagent, generateMinimalSubagent }
