#!/usr/bin/env bash
# scripts/ci/submodule-pointer-autorepair.sh
# SMI-6260 Wave 2 — post-merge TOCTOU closure for docs/internal's gitlink.
# Invoked by the `pointer-autorepair` job in
# .github/workflows/submodule-pointer-check.yml on every push to `main`
# touching a .gitmodules mount. Not named as a separate file in the plan's
# item 5 "Files" list, which names only the workflow YAML — added here to
# keep the workflow YAML's own complexity bounded and to match this repo's
# existing convention of a dedicated script behind a thin workflow step
# (see scripts/prod-deploy-cancel-monitor.sh + .github/workflows/prod-deploy-cancel-monitor.yml).
#
# Design (binding):
# docs/internal/implementation/smi-6260-docs-internal-pointer-regression-gate.md
# "TOCTOU closure" section. Only docs/internal (the sole v1 BLOCKING_MOUNTS
# entry in check-submodule-pointer.sh) drives auto-repair or issue-opening
# here — a non-blocking-mount warning never reaches this script's FAIL
# branch, matching check-submodule-pointer.sh's own --mode=block exit-code
# semantics (only a BLOCKING_MOUNTS failure sets the non-zero exit).
#
# Required env:
#   GITHUB_SHA        the pushed commit (T-side ref for check-submodule-pointer.sh)
#   BEFORE_SHA         resolved B_prev source (github.event.before, or the
#                      workflow's HEAD~1 fallback for a null/new-branch before)
#   SHADOW             '1' (default posture) suppresses only the R3 auto-repair
#                      PUSH — alerting/issue-opening still happens (per the
#                      plan's explicit shadow-mode-scope clarification)
#   MAIN_PUSH_PAT      may be empty — SKILLSMITH_MAIN_PUSH_PAT is unprovisioned
#                      as of this Wave 2 implementation (confirmed via
#                      `gh secret list`, see the Wave 2 report); empty means
#                      degrade to alert-only for R3 too
#   GH_TOKEN            used by `gh issue` calls (github.token is sufficient —
#                       issues:write, no push needed for issue creation)
#   GITHUB_REPOSITORY   owner/repo, for `gh issue --repo`

set -uo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
MOUNT="docs/internal"
MOUNT_DIR="$REPO_ROOT/$MOUNT"
OUTPUT_FILE="$(mktemp)"

: "${GITHUB_SHA:?GITHUB_SHA required}"
: "${BEFORE_SHA:?BEFORE_SHA required}"
SHADOW="${SHADOW:-1}"
MAIN_PUSH_PAT="${MAIN_PUSH_PAT:-}"
GITHUB_REPOSITORY="${GITHUB_REPOSITORY:-smith-horn/skillsmith}"

"$REPO_ROOT/scripts/ci/check-submodule-pointer.sh" \
    --mode=block \
    --ref="$GITHUB_SHA" \
    --before="$BEFORE_SHA" \
    >"$OUTPUT_FILE" 2>&1
EXIT_CODE=$?
cat "$OUTPUT_FILE"

if [ "$EXIT_CODE" -eq 0 ]; then
    echo "[pointer-autorepair] no blocking-mount violation on this push — nothing to do."
    exit 0
fi

FAIL_LINE="$(grep -E "^FAIL \[${MOUNT}\]: " "$OUTPUT_FILE" | head -1 || true)"
if [ -z "$FAIL_LINE" ]; then
    echo "[pointer-autorepair] non-zero exit but no blocking-mount FAIL line found for $MOUNT — nothing actionable (likely R-FETCH, already handled by the caller's own fetch-outcome gate)."
    exit 0
fi

RULE="$(printf '%s' "$FAIL_LINE" | sed -E 's/^FAIL \[[^]]+\]: (R[0-9]+):.*/\1/')"
echo "[pointer-autorepair] matched rule: $RULE"

# ---------------------------------------------------------------------------
# Deduped GitHub issue helper — dedupe key is the exact commit SHA this run
# is reacting to (a fresh regression on a later push always gets its own
# issue, even if an older one for a prior SHA is still open).
# ---------------------------------------------------------------------------
open_or_skip_issue() {
    _SPA_REMEDIATION="$1"
    _SPA_EXISTING="$(gh issue list --repo "$GITHUB_REPOSITORY" \
        --search "\"commit ${GITHUB_SHA}\" in:body" --state all \
        --json number -q '.[0].number' 2>/dev/null || echo "")"
    if [ -n "${_SPA_EXISTING:-}" ] && [ "$_SPA_EXISTING" != "null" ]; then
        echo "[pointer-autorepair] already reported as issue #${_SPA_EXISTING}, skipping"
        return 0
    fi

    # shellcheck disable=SC2016  # single-quoted ON PURPOSE: the backticked
    # `pointer-autorepair`/`main`/etc. spans are literal Markdown, not shell
    # command substitution — the %s placeholders are printf format specs,
    # substituted via printf's own args below, never shell-expanded.
    _SPA_BODY="$(printf '%s\n\nDetected by `pointer-autorepair` (SMI-6260) on push to `main`, commit %s.\n\n**Remediation**: %s\n\n_Auto-generated by `.github/workflows/submodule-pointer-check.yml` (SMI-6260)._' \
        "$FAIL_LINE" "$GITHUB_SHA" "$_SPA_REMEDIATION")"

    gh issue create --repo "$GITHUB_REPOSITORY" \
        --label submodule-pointer-regression \
        --title "docs/internal pointer regression on main (${RULE}) — commit ${GITHUB_SHA:0:7}" \
        --body "$_SPA_BODY" || echo "::warning::gh issue create failed for ${RULE} on ${GITHUB_SHA}"
}

if [ "$RULE" = "R3" ]; then
    # The only auto-repairable case: fast-forward the gitlink to T.
    BRANCH="$(git config -f "$REPO_ROOT/.gitmodules" --get submodule."$MOUNT".branch 2>/dev/null || echo main)"
    T_SHA="$(git -C "$MOUNT_DIR" rev-parse "origin/$BRANCH")"

    # No `set -e` in this script (the push result below needs explicit
    # if/else branching), so this sequence must fail loudly and stop here
    # rather than silently falling through to the push-or-shadow branch
    # below with a HEAD that never actually advanced (governance review
    # finding — a job with write access to main must never risk pushing a
    # stale HEAD because an earlier step in the same run silently failed).
    if ! git -C "$MOUNT_DIR" checkout --detach --quiet "$T_SHA" \
        || ! git -C "$REPO_ROOT" -c user.name="skillsmith-bot" -c user.email="bot@skillsmith.app" add "$MOUNT" \
        || ! git -C "$REPO_ROOT" -c user.name="skillsmith-bot" -c user.email="bot@skillsmith.app" \
            commit --quiet -m "chore(docs): fast-forward docs/internal pointer to ${T_SHA:0:7} [auto-repair SMI-6260]"; then
        echo "::error::[pointer-autorepair] failed to prepare the R3 repair commit (checkout/add/commit) — aborting without pushing or alerting on a stale HEAD; re-run the workflow"
        exit 1
    fi

    if [ "$SHADOW" = "1" ]; then
        echo "[pointer-autorepair] shadow mode — R3 detected, auto-repair PUSH suppressed, but still alerting (per plan's shadow-mode-scope clarification)."
        open_or_skip_issue "SHADOW MODE: would fast-forward to ${T_SHA} (commit prepared locally, not pushed). Once shadow mode ends, or manually now: \`./scripts/bump-docs-pointer.sh\`"
    elif [ -z "$MAIN_PUSH_PAT" ]; then
        echo "::warning::SKILLSMITH_MAIN_PUSH_PAT not provisioned — degrading to alert-only for this R3 detection."
        open_or_skip_issue "SKILLSMITH_MAIN_PUSH_PAT is not provisioned; auto-repair cannot push. Run manually: \`./scripts/bump-docs-pointer.sh\`"
    else
        if git -C "$REPO_ROOT" push "https://x-access-token:${MAIN_PUSH_PAT}@github.com/${GITHUB_REPOSITORY}.git" HEAD:main; then
            echo "[pointer-autorepair] pushed fast-forward repair to main: ${T_SHA}"
        else
            echo "::warning::auto-repair push failed — falling back to alerting"
            open_or_skip_issue "Auto-repair push failed (see workflow run log). Run manually: \`./scripts/bump-docs-pointer.sh\`"
        fi
    fi
    exit 0
fi

case "$RULE" in
    R1 | R5 | R6 | R7)
        open_or_skip_issue "Run \`./scripts/bump-docs-pointer.sh\` (see the rule message above for the exact target)."
        ;;
    R11)
        open_or_skip_issue "A maintainer must manually repair main's docs/internal pointer directly (see ADR-143's docs-internal-pointer-repair note) before R7 can validate new bumps against it."
        ;;
    R8)
        open_or_skip_issue "R8 should not occur on a push to main (PAT is always available server-side) — investigate the workflow run directly."
        ;;
    *)
        open_or_skip_issue "See the rule message above."
        ;;
esac

exit 0
