/**
 * @fileoverview Bundled-snapshot typosquat scan for `skill_validate` (SMI-6033 Wave 1, Gap 7).
 *
 * Extracted from validate.ts as a standalone, dependency-light function so it
 * can be unit-tested directly (no ToolContext / database), mirroring
 * `validate-bundled-scan.ts`'s pattern. Loads the checked-in, release-time
 * reference-name snapshot (`packages/mcp-server/src/assets/
 * typosquat-reference-snapshot.json`, generated by
 * `scripts/generate-typosquat-snapshot.ts`) via a plain `readFileSync` — no
 * network or DB call, keeping `skill_validate` fully offline. Runs the
 * already-built `scanTyposquat()` detector (`@skillsmith/core`, SMI-595)
 * against the skill's own declared name, at the SMI-595 default `warn`
 * enforcement mode, surfacing any finding as a `warning`-severity
 * `ValidationError` (never `error` — warn-tier, non-blocking, matching the
 * indexer-side wiring's enforcement mode).
 */
import { readFileSync, existsSync } from 'fs'
import { join, dirname } from 'path'
import { fileURLToPath } from 'url'
import { detectTyposquat, resolveTyposquatEnforcementMode } from '@skillsmith/core/security/scanner'
import type { ValidationError } from './validate.types.js'

const __filename = fileURLToPath(import.meta.url)
const __dirname = dirname(__filename)

/**
 * Path to bundled assets in the npm package (same dist-vs-src resolution as
 * `onboarding/install-assets.ts` — this file lives at the same `src/*`
 * depth, one level under the package root).
 */
function getAssetsDir(): string {
  const fromDistPath = join(__dirname, '..', '..', '..', 'src', 'assets')
  if (existsSync(fromDistPath)) {
    return fromDistPath
  }
  const fromSrcPath = join(__dirname, '..', 'assets')
  if (existsSync(fromSrcPath)) {
    return fromSrcPath
  }
  return fromDistPath
}

const SNAPSHOT_PATH = join(getAssetsDir(), 'typosquat-reference-snapshot.json')

interface TyposquatReferenceSnapshot {
  generatedAt: string | null
  source: string
  names: string[]
}

let cachedReferenceNames: ReadonlySet<string> | undefined

/**
 * Load the bundled reference-name snapshot (cached after first read — the
 * snapshot is a release-time asset, not something that changes mid-process).
 * Returns an empty set (no findings possible) if the snapshot is missing or
 * unparsable — never throws, so a corrupt/absent snapshot degrades to
 * "no typosquat check" rather than failing validation outright.
 */
function loadReferenceNames(): ReadonlySet<string> {
  if (cachedReferenceNames) return cachedReferenceNames

  try {
    const raw = readFileSync(SNAPSHOT_PATH, 'utf-8')
    const parsed = JSON.parse(raw) as TyposquatReferenceSnapshot
    cachedReferenceNames = new Set(
      Array.isArray(parsed.names) ? parsed.names.map((n) => n.toLowerCase()) : []
    )
  } catch {
    cachedReferenceNames = new Set()
  }

  return cachedReferenceNames
}

/**
 * Scan a skill's declared name (from its SKILL.md frontmatter) against the
 * bundled typosquat reference snapshot, returning a `warning`-severity
 * ValidationError per finding. No-op (returns []) when the snapshot has no
 * names (unwritten placeholder, or the frontmatter has no `name`).
 *
 * @param skillName the skill's own declared name (SKILL.md frontmatter `name`)
 */
export function scanTyposquatName(skillName: string | undefined): ValidationError[] {
  if (!skillName || !skillName.trim()) return []

  const referenceNames = loadReferenceNames()
  if (referenceNames.size === 0) return []

  const findings = detectTyposquat(
    skillName,
    referenceNames,
    resolveTyposquatEnforcementMode('warn')
  )

  return findings.map((finding) => ({
    field: 'name',
    message:
      `Possible typosquat: ${finding.message} ` +
      `See https://skillsmith.app/docs/security/scanner#typosquat`,
    severity: 'warning',
  }))
}
